apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    error_log  /var/log/nginx/error.log;
    events {}
    http {
      log_format main '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
      access_log    /var/log/nginx/access.log main;
      server {
          listen       80;
          server_name  localhost;

          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
          }
          location /images {
            root   /usr/share/nginx/html/data;
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondnginx--deployment
  labels:
    app: secondNginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secondNginx
  template:
    metadata:
      labels:
        app: secondNginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: log
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: secondnginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: secondNginx

